# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--no-cache'
  - '--build-arg=BASE_IMAGE=launcher.gcr.io/google/openjdk8'
  - '--build-arg=DOCKER_VERSION=5:18.09.0~3-0~debian-stretch'
  - '--tag=gcr.io/$PROJECT_ID/javac:11'
  - '--tag=gcr.io/$PROJECT_ID/javac'
  - '--tag=gcr.io/$PROJECT_ID/java/javac:11'
  - '--tag=gcr.io/$PROJECT_ID/java/javac'
  - '.'
  waitFor: ['-']
  id: 'BUILD_JDK_11'

# Test that javac and docker are installed, for all built images, and that apt-get update will work
# in child images

- name: 'gcr.io/$PROJECT_ID/javac:11'
  args: ['-version']
  waitFor: ['BUILD_JDK_11']
- name: 'gcr.io/$PROJECT_ID/javac:11'
  entrypoint: 'docker'
  args: ['version']
  waitFor: ['BUILD_JDK_11']
- name: 'gcr.io/$PROJECT_ID/javac:11'
  entrypoint: 'apt-get'
  args: ['update']
  waitFor: ['BUILD_JDK_11']

images:
- 'gcr.io/$PROJECT_ID/javac:11'
- 'gcr.io/$PROJECT_ID/javac'
- 'gcr.io/$PROJECT_ID/java/javac:11'
- 'gcr.io/$PROJECT_ID/java/javac'